### ISSUE TITLE
[Auto-entrepreneur] Bug à corriger: ACRE indisponible pour activité commerciale ou artisanale de services, même pour entreprise de moins de 1 ans

### ISSUE THREAD

**Issue by glopezrios** [betagouv/mon-entreprise#3054]
Dans le simulateur pour auto-entrepreneur, quand:

- on répond "commerciale" à la question "Quelle est la nature de votre activité principale ?"
- on répond "prestation de services" à la question "Quelle est le type d'activité principale de l'entreprise ?"
- on rentre une date de création de l'entreprise datant de moins de un an (par exemple le 01/01/2024)

alors 
- la question "Bénéficiez-vous de l'ACRE ?" n'apparait pas au fil du questionnaire et est introuvable dans la liste des questions disponible en cliquant sur "Modifier mes réponses"
- l'ACRE n'est pas activée (le taux de cotisation est le taux normal)
- mais pourtant sous les résultats, dans la rubrique "Retraite : droits acquis sur l'année" il y a la phrase encadré de jaune "L’exonération ACRE n'a aucune incidence sur la détermination des droits à la retraite de base et complémentaire des auto-entrepreneurs"
- et surtout, quand on va dans les pages de documentation (cf. capture d'écran), on voit qu'il est appliqué un "taux ACRE > Service BIC" qui correspond au taux normal (et non au taux réduit, qui devait être divisé par deux). Et quand on clique sur[ "taux ACRE > Service BIC"](https://mon-entreprise.urssaf.fr/documentation/dirigeant/auto%E2%80%91entrepreneur/cotisations-et-contributions/cotisations/taux-ACRE/service-BIC), on arrive à un message d'erreur et impossible de faire marche arrière: on perd toutes les données rentrées dans le simulateur.

Voici un lien de partage transmis par un usager, qui permet de constater le problème:
https://mon-entreprise.urssaf.fr/simulateurs/auto-entrepreneur?dirigeant+.+auto-entrepreneur+.+chiffre+d%27affaires=70000%E2%82%AC%2Fan&dirigeant+.+auto-entrepreneur+.+imp%C3%B4t+.+versement+lib%C3%A9ratoire=non&entreprise+.+activit%C3%A9+.+nature=%27commerciale%27&entreprise+.+activit%C3%A9s+.+service+ou+vente=%27service%27&entreprise+.+date+de+cr%C3%A9ation=%2701%2F01%2F2024%27&imp%C3%B4t+.+m%C3%A9thode+de+calcul=%27taux+neutre%27&unite=%E2%82%AC%2Fan

Ce bug concerne aussi les prestations de service classées en activité artisanale.

Pour les autres types d'activité, il semblerait que l'ACRE soit appliquée normalement.

![2024-07-29_14h45_12](https://github.com/user-attachments/assets/62fa0c62-6184-43ec-97bd-1cf747f53fd0)

**Comment by glopezrios** [comment]
Précision supplémentaire:
Dans la page de documentation, quand on clique sur "taux ACRE > Service BIC", on arrive à une page indiquant un message d'erreur (cf. capture d'écran). Et quand on envoie un message depuis cette page, voici ce que l'on reçoit sur Crisp:

https://mon-entreprise.urssaf.fr?unite=%E2%82%AC%2Fmois

{
"name": "PrivateRule",
"message": "\n[ Règle privée ]\n➡️ Dans la règle \"dirigeant . auto-entrepreneur . cotisations et contributions . cotisations . taux ACRE\"\n⚠️ La règle dirigeant . auto-entrepreneur . cotisations et contributions . cotisations . taux ACRE est une règle privée.",
"stack": "PrivateRule: \n[ Règle privée ]\n➡️ Dans la règle \"dirigeant . auto-entrepreneur . cotisations et contributions . cotisations . taux ACRE\"\n⚠️ La règle dirigeant . auto-entrepreneur . cotisations et contributions . cotisations . taux ACRE est une règle privée.\n at N8.getRule (https://mon-entreprise.urssaf.fr/assets/vendor.b3336feb.js:67:247742)\n at Tr (https://mon-entreprise.urssaf.fr/assets/sentry.02c9ba76.js:1:206599)\n at NX (https://mon-entreprise.urssaf.fr/assets/vendor.b3336feb.js:97:117766)\n at eb (https://mon-entreprise.urssaf.fr/assets/vendor.b3336feb.js:40:63897)\n at z_ (https://mon-entreprise.urssaf.fr/assets/vendor.b3336feb.js:40:116398)\n at V_ (https://mon-entreprise.urssaf.fr/assets/vendor.b3336feb.js:40:112159)\n at 7 (https://mon-entreprise.urssaf.fr/assets/vendor.b3336feb.js:40:112087)\n at lf (https://mon-entreprise.urssaf.fr/assets/vendor.b3336feb.js:40:111941)\n at Rv (https://mon-entreprise.urssaf.fr/assets/vendor.b3336feb.js:40:108306)\n at j (https://mon-entreprise.urssaf.fr/assets/vendor.b3336feb.js:40:107257)\n at _ (https://mon-entreprise.urssaf.fr/assets/vendor.b3336feb.js:32:1540)\n at MessagePort.E (https://mon-entreprise.urssaf.fr/assets/vendor.b3336feb.js:32:1899)",
"componentStack": "\n at WT (https://mon-entreprise.urssaf.fr/assets/vendor.b3336feb.js:24:5265)\n at ej (https://mon-entreprise.urssaf.fr/assets/vendor.b3336feb.js:58:3909)\n at hne (https://mon-entreprise.urssaf.fr/assets/vendor.b3336feb.js:58:7078)\n at AS (https://mon-entreprise.urssaf.fr/assets/sentry.02c9ba76.js:1:693892)\n at G1 (https://mon-entreprise.urssaf.fr/assets/sentry.02c9ba76.js:1:80222)\n at div\n at xne (https://mon-entreprise.urssaf.fr/assets/vendor.b3336feb.js:67:28026)\n at J0 (https://mon-entreprise.urssaf.fr/assets/sentry.02c9ba76.js:1:209698)\n at div\n at yq (https://mon-entreprise.urssaf.fr/assets/vendor.b3336feb.js:67:332448)\n at gq (https://mon-entreprise.urssaf.fr/assets/vendor.b3336feb.js:67:332078)\n at bq\n at WT (https://mon-entreprise.urssaf.fr/assets/vendor.b3336feb.js:24:5265)\n at uj (https://mon-entreprise.urssaf.fr/assets/vendor.b3336feb.js:58:6511)\n at mne (https://mon-entreprise.urssaf.fr/assets/vendor.b3336feb.js:67:1091)\n at t (https://mon-entreprise.urssaf.fr/assets/vendor.b3336feb.js:67:42478)\n at Xv (https://mon-entreprise.urssaf.fr/assets/sentry.02c9ba76.js:1:223505)\n at ure (https://mon-entreprise.urssaf.fr/assets/vendor.b3336feb.js:97:2919)\n at une (https://mon-entreprise.urssaf.fr/assets/vendor.b3336feb.js:40:147730)\n at WT (https://mon-entreprise.urssaf.fr/assets/vendor.b3336feb.js:24:5265)\n at div\n at y (https://mon-entreprise.urssaf.fr/assets/vendor.b3336feb.js:67:29997)\n at xne (https://mon-entreprise.urssaf.fr/assets/vendor.b3336feb.js:67:28026)\n at yne (https://mon-entreprise.urssaf.fr/assets/vendor.b3336feb.js:67:24680)\n at Y0 (https://mon-entreprise.urssaf.fr/assets/sentry.02c9ba76.js:1:210365)\n at Qg (https://mon-entreprise.urssaf.fr/assets/sentry.02c9ba76.js:1:36742)\n at Kg (https://mon-entreprise.urssaf.fr/assets/sentry.02c9ba76.js:1:35746)\n at Qv (https://mon-entreprise.urssaf.fr/assets/sentry.02c9ba76.js:1:223022)\n at NS (https://mon-entreprise.urssaf.fr/assets/sentry.02c9ba76.js:1:694980)\n at Xte (https://mon-entreprise.urssaf.fr/assets/vendor.b3336feb.js:17:6497)\n at i\n at HT (https://mon-entreprise.urssaf.fr/assets/vendor.b3336feb.js:24:3582)\n at profiler(i)"

![2024-07-30_11h34_27](https://github.com/user-attachments/assets/ab1f387d-f441-4446-8f63-0be8f836b3c4)
